/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MapRouteImport } from './routes/map'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgronomistRouteImport } from './routes/agronomist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScorecardIdRouteImport } from './routes/scorecard.$id'
import { Route as FarmersIdRouteImport } from './routes/farmers.$id'
import { Route as ApiUssdCallbackRouteImport } from './routes/api/ussd-callback'
import { Route as ApiClimateRouteImport } from './routes/api/climate'

const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgronomistRoute = AgronomistRouteImport.update({
  id: '/agronomist',
  path: '/agronomist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardIdRoute = ScorecardIdRouteImport.update({
  id: '/scorecard/$id',
  path: '/scorecard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersIdRoute = FarmersIdRouteImport.update({
  id: '/farmers/$id',
  path: '/farmers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUssdCallbackRoute = ApiUssdCallbackRouteImport.update({
  id: '/api/ussd-callback',
  path: '/api/ussd-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClimateRoute = ApiClimateRouteImport.update({
  id: '/api/climate',
  path: '/api/climate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agronomist': typeof AgronomistRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRoute
  '/graph': typeof GraphRoute
  '/logs': typeof LogsRoute
  '/map': typeof MapRoute
  '/partners': typeof PartnersRoute
  '/readiness': typeof ReadinessRoute
  '/api/climate': typeof ApiClimateRoute
  '/api/ussd-callback': typeof ApiUssdCallbackRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/scorecard/$id': typeof ScorecardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agronomist': typeof AgronomistRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRoute
  '/graph': typeof GraphRoute
  '/logs': typeof LogsRoute
  '/map': typeof MapRoute
  '/partners': typeof PartnersRoute
  '/readiness': typeof ReadinessRoute
  '/api/climate': typeof ApiClimateRoute
  '/api/ussd-callback': typeof ApiUssdCallbackRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/scorecard/$id': typeof ScorecardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agronomist': typeof AgronomistRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRoute
  '/graph': typeof GraphRoute
  '/logs': typeof LogsRoute
  '/map': typeof MapRoute
  '/partners': typeof PartnersRoute
  '/readiness': typeof ReadinessRoute
  '/api/climate': typeof ApiClimateRoute
  '/api/ussd-callback': typeof ApiUssdCallbackRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/scorecard/$id': typeof ScorecardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agronomist'
    | '/auth'
    | '/dashboard'
    | '/farmer'
    | '/graph'
    | '/logs'
    | '/map'
    | '/partners'
    | '/readiness'
    | '/api/climate'
    | '/api/ussd-callback'
    | '/farmers/$id'
    | '/scorecard/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agronomist'
    | '/auth'
    | '/dashboard'
    | '/farmer'
    | '/graph'
    | '/logs'
    | '/map'
    | '/partners'
    | '/readiness'
    | '/api/climate'
    | '/api/ussd-callback'
    | '/farmers/$id'
    | '/scorecard/$id'
  id:
    | '__root__'
    | '/'
    | '/agronomist'
    | '/auth'
    | '/dashboard'
    | '/farmer'
    | '/graph'
    | '/logs'
    | '/map'
    | '/partners'
    | '/readiness'
    | '/api/climate'
    | '/api/ussd-callback'
    | '/farmers/$id'
    | '/scorecard/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgronomistRoute: typeof AgronomistRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FarmerRoute: typeof FarmerRoute
  GraphRoute: typeof GraphRoute
  LogsRoute: typeof LogsRoute
  MapRoute: typeof MapRoute
  PartnersRoute: typeof PartnersRoute
  ReadinessRoute: typeof ReadinessRoute
  ApiClimateRoute: typeof ApiClimateRoute
  ApiUssdCallbackRoute: typeof ApiUssdCallbackRoute
  FarmersIdRoute: typeof FarmersIdRoute
  ScorecardIdRoute: typeof ScorecardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agronomist': {
      id: '/agronomist'
      path: '/agronomist'
      fullPath: '/agronomist'
      preLoaderRoute: typeof AgronomistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard/$id': {
      id: '/scorecard/$id'
      path: '/scorecard/$id'
      fullPath: '/scorecard/$id'
      preLoaderRoute: typeof ScorecardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/$id': {
      id: '/farmers/$id'
      path: '/farmers/$id'
      fullPath: '/farmers/$id'
      preLoaderRoute: typeof FarmersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ussd-callback': {
      id: '/api/ussd-callback'
      path: '/api/ussd-callback'
      fullPath: '/api/ussd-callback'
      preLoaderRoute: typeof ApiUssdCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/climate': {
      id: '/api/climate'
      path: '/api/climate'
      fullPath: '/api/climate'
      preLoaderRoute: typeof ApiClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgronomistRoute: AgronomistRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FarmerRoute: FarmerRoute,
  GraphRoute: GraphRoute,
  LogsRoute: LogsRoute,
  MapRoute: MapRoute,
  PartnersRoute: PartnersRoute,
  ReadinessRoute: ReadinessRoute,
  ApiClimateRoute: ApiClimateRoute,
  ApiUssdCallbackRoute: ApiUssdCallbackRoute,
  FarmersIdRoute: FarmersIdRoute,
  ScorecardIdRoute: ScorecardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
