/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScorecardIdRouteImport } from './routes/scorecard.$id'
import { Route as FarmersIdRouteImport } from './routes/farmers.$id'
import { Route as ApiClimateRouteImport } from './routes/api/climate'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardIdRoute = ScorecardIdRouteImport.update({
  id: '/scorecard/$id',
  path: '/scorecard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersIdRoute = FarmersIdRouteImport.update({
  id: '/farmers/$id',
  path: '/farmers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClimateRoute = ApiClimateRouteImport.update({
  id: '/api/climate',
  path: '/api/climate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRoute
  '/logs': typeof LogsRoute
  '/api/climate': typeof ApiClimateRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/scorecard/$id': typeof ScorecardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRoute
  '/logs': typeof LogsRoute
  '/api/climate': typeof ApiClimateRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/scorecard/$id': typeof ScorecardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRoute
  '/logs': typeof LogsRoute
  '/api/climate': typeof ApiClimateRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/scorecard/$id': typeof ScorecardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/farmer'
    | '/logs'
    | '/api/climate'
    | '/farmers/$id'
    | '/scorecard/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/farmer'
    | '/logs'
    | '/api/climate'
    | '/farmers/$id'
    | '/scorecard/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/farmer'
    | '/logs'
    | '/api/climate'
    | '/farmers/$id'
    | '/scorecard/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FarmerRoute: typeof FarmerRoute
  LogsRoute: typeof LogsRoute
  ApiClimateRoute: typeof ApiClimateRoute
  FarmersIdRoute: typeof FarmersIdRoute
  ScorecardIdRoute: typeof ScorecardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard/$id': {
      id: '/scorecard/$id'
      path: '/scorecard/$id'
      fullPath: '/scorecard/$id'
      preLoaderRoute: typeof ScorecardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/$id': {
      id: '/farmers/$id'
      path: '/farmers/$id'
      fullPath: '/farmers/$id'
      preLoaderRoute: typeof FarmersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/climate': {
      id: '/api/climate'
      path: '/api/climate'
      fullPath: '/api/climate'
      preLoaderRoute: typeof ApiClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FarmerRoute: FarmerRoute,
  LogsRoute: LogsRoute,
  ApiClimateRoute: ApiClimateRoute,
  FarmersIdRoute: FarmersIdRoute,
  ScorecardIdRoute: ScorecardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
